### ISSUE TITLE
minor translation issues

### ISSUE THREAD

**Issue by everyday3419** [KotatsuApp/website#2]
Hello! I noticed that when you change the language, a part of the FeatureTitle remains unchanged because the values of the title and subtitle fields are static.

![image](https://github.com/KotatsuApp/website/assets/115849208/497fcf7d-085e-4e41-9e9c-1fdf127f0c90)

Possible solutions could include:

**FeatureTitle.vue**
```vue
<script setup lang="ts">
export interface FeatureTitle {
  featureTitle: string;
  featureSubtitle: string;
}

defineProps<{
  data: FeatureTitle;
}>();
</script>

<template>
  <div class="FeatureTitle">
    <div class="container">
      <p v-if="data.featureTitle" class="title">
        <span v-html="data.featureTitle" class="title"></span>
      </p>
      <h1 v-if="data.featureSubtitle" class="subtitle">
        <span v-html="data.featureSubtitle" class="subtitle"></span>
      </h1>
    </div>
  </div>
</template>
```

**Home.vue**
```vue
<template>
  <template v-if="fm.main">
    <div class="container">
      <HomeHero :data="fm.main" />
      <FeatureTitle :data="fm.main" />
      <Features :features="fm.main.features" />
    </div>
  </template>
</template>
```

**ua/index.md**
```
main:
  title: Манґа у вашій кишені
  tagline: Проста і зручна програма для читання манґи з відкритим вихідним кодом від спільноти і для спільноти, де ви можете знайти і прочитати свою улюблену манґу простіше, ніж будь-коли.
  image:
    alt: Kotatsu Logo
    light: /phone_light.webp
    dark: /phone_dark.webp
  actions:
    - theme: brand
      text: Завантажити
      link: /ua/download/
    - theme: alt
      text: Посібники
      link: /ua/manuals/guides/getting-started/
  featureTitle: На що здатний Kotatsu?
  featureSubtitle: I ось на що він здатний!
  features:
    - image:
        alt: Feature Sources
        light: /img/feature_sources-light.webp
        dark: /img/feature_sources-dark.webp
      title: Величезна кількість джерел
      details: Підтримує понад 500+ джерел
```
